src: use header from lib instead of repeating the declaration
To fix:

MSVS: CMake, VS2022, Debug, x64, Schannel, Shared, DEBUGBUILD=ON, CURLDEBUG=OFF
```
unity_0_c.obj : error LNK2019: unresolved external symbol curl_easy_perform_ev referenced in function serial_transfers [curl\_bld\src\curl.vcxproj]
    10>curl\_bld\src\curl.exe : fatal error LNK1120: 1 unresolved externals
```
Ref: https://ci.appveyor.com/project/curlorg/curl/builds/49852346/job/v71t14kc6os47s31#L261

mingw-w64: CMake, mingw-w64, gcc 13, Debug, x64, Schannel, Shared, DEBUGBUILD=ON, CURLDEBUG=OFF
```
CMakeFiles/curl.dir/objects.a(unity_0_c.c.obj): in function `serial_transfers':
1447C:/projects/curl/src/tool_operate.c:2495:(.text+0x18777): undefined reference to `curl_easy_perform_ev'
```
Ref: https://ci.appveyor.com/project/curlorg/curl/builds/49852346/job/lig8hj3570knux38#L197

But, this was not enough because we're using libcurl.def for exporting
functions and curl_easy_perform_ev() is not on the list.

The reason why it worked before is because CMake has special logic
to disable symbol hiding for ENABLE_CURLDEBUG. We must now do the same
for ENABLE_DEBUGBUILD. But, that's not so simple either because the
only way to test DEBUGBUILD without CURLDEBUG, is passing -DDEBUGBUILD
via CMAKE_C_FLAGS, in which case ENABLE_DEBUGBUILD is OFF.

Ref: 6cf8413e31629183b3c749aa2a17d24be14cbca1

~~Also CURL_EXTERN not necessary for curl_easy_perform_ev, since we rely
on disabling symbol hiding to export this. Just like for curl_dbg_*()
functions used for memory tracking.~~ [I misread this, CURL_EXTERN is
actually required for non-Windows/autotools systems.]

But, did this ever work for autotools / Windows builds?